TRAEFIK_SUB_DOMAIN: web
DOMAIN_NAME: devops.harimi.ir
# ACME variables
TRAEFIK_ACME_EMAIL: gharimi.rh@gmail.com

# set restart policy
RESTART_POLICY: on-failure
    
#  web auth information.
#  how to generate password: 
#  echo azddqmbwvcB8RSDYP8fn2H7UDoq5Vk | htpasswd -s -n -i MeCan
WEB_AUTH_USER: MeCan
WEB_AUTH_PASS: "{SHA}CdKDmnQDKnggA1iGsBvaGJeTSIE="

# Hostname
HOSTNAME: sw1-server

