services:
  redis-master:
    image: bitnami/redis:7.2
    hostname: redis-master
    networks:
      - redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
    deploy:
      replicas: 1

  redis-slave:
    image: bitnami/redis:7.2
    hostname: redis-slave.{{.Task.Slot}}
    networks:
      - redis
        #   depends_on:
        # - redis-master
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_REPLICA_IP=redis-slave.{{.Task.Slot}}
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1

  redis-sentinel:
    image: bitnami/redis-sentinel:7.2
    networks:
      - redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=5000
    deploy:
      mode: global
    depends_on:
      - redis-master

  proxy:
    image: haproxy:2.9.6-alpine
    hostname: redis
    configs:
      - source: haproxy
        target: /usr/local/etc/haproxy/haproxy.cfg
    networks:
      - redis
      - web_net
      - pg_net
      - mariadb_galera-network
    depends_on:
      - redis-sentinel
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web_net"
        - "traefik.http.routers.haproxy.entrypoints=http"
        - "traefik.http.routers.haproxy.rule=Host(`${HAPROXY_SUB}.${DOMAIN}`)"
        - "traefik.http.middlewares.web-auth.basicauth.users=${HAPROXY_AUTH_USER}\
          :${HAPROXY_AUTH_PASS}" #- "traefik.http.routers.haproxy-secure.middlewares=web-auth"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.haproxy-secure.entrypoints=https"
        - "traefik.http.routers.haproxy-secure.rule=Host(`${HAPROXY_SUB}.${DOMAIN\
          }`)"
        - "traefik.http.routers.haproxy-secure.middlewares=secure@file,https-redi\
          rect,web-auth"
        - "traefik.http.routers.haproxy-secure.tls=true"
        - "traefik.http.routers.haproxy-secure.tls.options=default"
        - "traefik.http.routers.haproxy-secure.tls.certresolver=mycert"
        - "traefik.http.services.haproxy.loadbalancer.server.port=9000"

networks:
  redis:
    driver: overlay
    name: redis
    external: true
  web_net:
    driver: overlay
    name: web_net
    external: true
  pg_net:
    driver: overlay
    name: pg_net
    external: true
  mariadb_galera-network:
    name: mariadb_galera-network
    external: true
    driver: overlay

configs:
  haproxy:
    file: ./haproxy.cfg
