---
#- name: Create a new virtual machine
#  community.vmware.vmware_guest:
#    hostname: "{{ esxi_host }}"
#    username: "{{ esxi_user }}"
#    password: "{{ esxi_password }}"
#    validate_certs: no
#    datacenter: "{{ datacenter_name }}"
#    cluster: "{{ cluster_name }}"
#    name: "{{ vm_name }}"
#    template: "{{ vm_template }}"
#    datastore: "{{ datastore_name }}"
#    folder: "{{ folder_name }}"  # Optional: Specify folder path for VM
#    networks:
#      - name: "{{ network_name }}"
#    hardware:
#      memory_mb: 2048
#      num_cpus: 2
#      disk:
#        - size_gb: 20
#          type: thin
#    state: poweredon
#  delegate_to: localhost
#  register: vm_result
#
#- name: Display VM result
#  debug:
#    var: vm_result
- name: create vm on esxi 
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    folder: "{{ folder_name }}"
    name: "{{ vm_name }}"
    disk:
      - size_gb: 20
        type: thin
        datastore: "{{ datastore_name }}"
    cdrom:
      type: "iso"
      iso_path: "{{ iso_path }}"
    networks:
      - name: "{{ network_name }}"
    hardware:
      memory_mb: "{{ memory_mb }}"
      num_cpus: "{{ num_cpus }}"
    state: poweredon
  delegate_to: localhost

