---
- name: Hardening
  hosts: all
  gather_facts: true
  ignore_errors: true
  become: true
  become_method: ansible.builtin.sudo
  roles:
    - role: harden
      tags: harden
      
    - role: traefik
      tags: traefik

    - role: nexus
      tags: nexus

    - role: docker
      tags: docker
