all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    webservers:
      hosts:
        harden-server1:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 37.32.14.213
          ansible_user: debian
          ansible_port: 3232

        harden-server2:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 159.69.88.202
          ansible_user: root
          ansible_port: 3232
        
        harden-server3:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 159.69.202.213
          ansible_user: root
          ansible_port: 3232

    dbservers:
      hosts:
        harden-server4:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 37.32.12.155
          ansible_user: debian
          ansible_port: 3232
