all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    webservers:
      hosts:
        harden-server1:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 37.32.10.30
          ansible_user: debian
          ansible_port: 22

        harden-server2:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 37.32.11.32
          ansible_user: debian
          ansible_port: 22
        
        harden-server3:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 37.32.8.72
          ansible_user: debian
          ansible_port: 22

        harden-server4:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 37.32.11.22
          ansible_user: ubuntu
          ansible_port: 22

        harden-server5:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 37.32.8.180
          ansible_user: ubuntu
          ansible_port: 22

        harden-server6:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 5.34.195.115
          ansible_user: ubuntu
          ansible_port: 22

        harden-server7:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 5.34.192.236
          ansible_user: ubuntu
          ansible_port: 22

        harden-server8:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 5.34.195.46
          ansible_user: debian
          ansible_port: 22

        harden-server9:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 5.34.193.29
          ansible_user: debian
          ansible_port: 22

    dbservers:
      hosts:
        harden-server10:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 5.34.195.216
          ansible_user: ubuntu
          ansible_port: 22
