all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    webservers:
      hosts:
        harden-server1:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 37.32.11.236
          ansible_user: debian
          ansible_port: 3232

        harden-server2:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 37.32.14.84
          ansible_user: debian
          ansible_port: 3232
        
        harden-server4:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 37.32.9.147
          ansible_user: ubuntu
          ansible_port: 3232

    dbservers:
      hosts:
        harden-server3:
          #ansible_become_password: "1qaz!QAZ"
          ansible_host: 5.34.201.167
          ansible_user: ubuntu
          ansible_port: 3232
