---
# handlers file for harden
- name: Restart_SSH
  systemd:
    name: sshd
    state: restarted
    enabled: yes

# handlers file for fail2ban
- name: restart fail2ban (with service)
  service:
    name: fail2ban
    state: restarted
  listen: "restart fail2ban"
  when: ansible_service_mgr != 'systemd'

- name: restart fail2ban (with systemd)
  systemd:
    name: fail2ban
    state: restarted
  listen: "restart fail2ban"
  when: ansible_service_mgr == 'systemd'

- name: Applying Kernel parameters
  become: true
  ansible.builtin.command:
    cmd: sysctl --system
   
- name: restart auditd
  systemd:
    name: auditd
    state: restarted
    enabled: yes

- name: generate auditd
  become: true
  ansible.builtin.command: augenrules      

- name: Restart ntp
  systemd:
    name: ntp
    state: restarted


- name: Restart_iptables
  systemd:
    name: iptables.service
    enabled: true
    state: restarted
