services:
  minio:
    image: minio/minio:latest
    networks:
      - web_net
      - minio
    volumes:
      - minio-data:/data
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      # Do NOT use MINIO_DOMAIN or MINIO_SERVER_URL with Traefik.
      # All Routing is done by Traefik, just tell minio where to redirect to.
      - MINIO_BROWSER_REDIRECT_URL=http://minio.devops.harimi.ir
    deploy:
      placement:
        constraints:
          - node.hostname == node1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=web_net"
        - "traefik.http.routers.minio.entrypoints=http"
        - "traefik.http.routers.minio.rule=Host(`${MINIO_SUB}.${DOMAIN}`)"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.minio-secure.entrypoints=https"
        - "traefik.http.routers.minio-secure.rule=Host(`${MINIO_SUB}.${DOMAIN}`)"
        - "traefik.http.routers.minio-secure.middlewares=secure@file,https-redirect"
        - "traefik.http.routers.minio-secure.tls.certresolver=mycert"
        - "traefik.http.services.minio.loadbalancer.server.port=9001"
        - "traefik.http.routers.minio-secure.tls=true"


  createbuckets:
    image: quay.io/minio/mc:${MINIO_MC_VERSION:-latest}
    depends_on:
      - minio
    networks:
      - minio
    configs:
      - source: backup-policy
        target: /tmp/backup-policy.json
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    entrypoint: >
      /bin/bash -c "
        sleep 10 ;
        /usr/bin/mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD ;
        for bucket in $BUCKETS ; do
          if ! /usr/bin/mc ls myminio/$$bucket ; then
            /usr/bin/mc mb myminio/$$bucket ;
            /usr/bin/mc policy set public myminio/$$bucket ;
          fi ;
        done ;
        if ! /usr/bin/mc admin policy info myminio backup-policy; then
          /usr/bin/mc admin policy create myminio backup-policy /tmp/backup-policy.json;
        fi;
        if ! /usr/bin/mc admin user info myminio $MINIO_BACKUP_USER; then
          /usr/bin/mc admin user add myminio $MINIO_BACKUP_USER $MINIO_BACKUP_PASSWORD;
          /usr/bin/mc admin policy attach myminio backup-policy --user $MINIO_BACKUP_USER
        fi;
        exit 0;
      "



volumes:
  minio-data:
    name: minio_data

networks:
  web_net:
    external: true
    name: web_net

  minio:
    name: minio
    external: false

configs:
  backup-policy:
    file: ./backup-policy.json

