---
- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install multiple packages using apt with loop
  package:
    name: "{{ item }}"
    state: present
      #update_cache: true
  loop:
    - curl
    - wget
    - vim
    - git
    - tree
    - bash-completion
    - tmux
    - fail2ban
    - lynis
    - iptables-persistent
    - ntp
    - debsums
    - dkms
    - linux-headers-$(uname -r)
    - build-essential
    - apt-show-versions
    - apt-listchanges
    - auditd
    - libpam-pwquality
    - rkhunter
    - clamav
    - aptitude
    - libpam-tmpdir
    - network-manager
    - python-is-python3
    - python3.11-venv
    - python3-systemd
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - zsh
    

- name: run aptitued purge
  ansible.builtin.command:
    cmd: aptitude purge
